- name: checking for proper repos
  shell: rpm -Uvh http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm
  sudo: yes

- name: installing Zookeeper
  yum: name={{ item }} state=present
  with_items:
    - zookeeper-server
    - zookeeper
  sudo: yes

- name: check for working directory
  file: path=/var/lib/zookeeper state=directory owner=zookeeper group=zookeeper
  sudo: yes

- name: initializing Zookeeper
  shell: zookeeper-server-initialize --myid={{ zookeeper_id }}
  sudo: yes
  sudo_user: zookeeper

- name: starting Zookeeper
  service: name=zookeeper-server state=started
  sudo: yes
