- name: checking for proper repos
  shell: rpm -Uvh {{ cloudera_repo_rpm }}

- name: installing Zookeeper
  yum: name={{ item }} state=present
  with_items:
    - zookeeper-server
    - zookeeper

- name: check for working directory
  file: path={{ zookeeper_data_dir }} state=directory owner={{ zookeeper_user }} group={{ zookeeper_group }}

- name: initializing Zookeeper
  shell: '"{{ zookeeper_initialize }}" --myid="{{ zookeeper_id }}"'
  sudo: yes
  sudo_user: "{{ zookeeper_user }}"

- name: starting Zookeeper
  service: name={{ zookeeper_service_name }} state=started
