- name: installing Zookeeper
  yum: name={{ item }} state=present
  with_items:
    - zookeeper-server
    - zookeeper
  sudo: yes

- name: starting Zookeeper
  service: name=zookeeper-server state=started
  sudo: yes
