- name: Clone Marathon from repository
  git: repo=https://github.com/mesosphere/marathon.git dest=/opt/marathon
  sudo: yes

- name: check for 'daemonize'
  yum: name=https://forensics.cert.org/centos/cert/7/x86_64/daemonize-1.7.3-7.el7.x86_64.rpm state=present
  sudo: yes

- name: adding repo in order to install 'sbt'
  shell: curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
  sudo: yes

- name: installing 'sbt'
  yum: name=sbt state=present
  sudo: yes

- name: compiling mesosphere
  shell: sbt assembly
  sudo: yes

- name: start Marathon
  shell: daemonize /opt/marathon/bin/start --master zk://{{ mesos_master }}:2181/mesos --zk zk://{{ mesos_master }}:2181/marathon
  sudo: yes
