- name: Clone Marathon from repository
  git: repo={{ marathon_repo_sources_git }} dest={{ marathon_sources_local }}

- name: check for 'daemonize'
  yum: name={{ daemonize_rpm }} state=present

- name: adding repo in order to install 'sbt'
  shell: "{{ shell_repo_sbt }}"

- name: installing 'sbt'
  yum: name=sbt state=present

- name: compiling Marathon
  command: chdir={{ marathon_sources_local }} sbt package

- name: start Marathon
  shell: daemonize {{ marathon_sources_local }}/bin/start --master {{ mesos_master }}:5050 --zk zk://{{ mesos_master }}:2181/marathon
