- hosts: all
  roles:
     - mesos
  remote_user: testusr
  sudo: yes

- hosts: mesosmaster
  roles:
    - marathon
    - kafka
  remote_user: testusr
  sudo: yes

- hosts: all
  roles:
    - mesos-slave
  remote_user: testusr
  sudo: yes

- hosts: mesosmaster
  roles:
    - spark
  remote_user: testusr
  sudo: yes
