- name: Clonning Kafka Mesos from repo
  git: repo={{kafka_mesos_git_repo}} dest={{kafka_path}}

- name: building Kafka
  shell: "{{ item }}"
  args:
    chdir: "{{ kafka_path }}"
  with_items:
    - ./gradlew jar

- name: downloading Kafka
  get_url: url={{kafka_dist}} dest={{kafka_path}}/{{kafka_dist_name}}

- name: copying properties file in order to be able to start Kafka
  copy: src=kafka-mesos.properties.j2 dest={{kafka_path}}/kafka-mesos.properties

- name: check for 'daemonize'
  yum: name={{ daemonize_rpm }} state=present

- name: exporting Mesos shared library
  shell: export MESOS_NATIVE_JAVA_LIBRARY={{ mesos_compile_dir }}/lib/libmesos.so

- name: starting Kafka
  shell: cd {{kafka_path}} && daemonize bash kafka-mesos.sh scheduler
