- name: Clonning Kafka Mesos from repo
  git: repo={{kafka_mesos_git_repo}} dest={{kafka_path}}

- name: building Kafka
  shell: "{{ item }}"
  args:
    chdir: "{{ kafka_path }}"
  with_items:
    - ./gradlew jar

- name: downloading Kafka
  get_url: url={{kafka_dist}} dest={{kafka_path}}/{{kafka_dist_name}}

- name: copying properties file in order to be able to start Kafka
  copy: src=kafka-mesos.properties.j2 dest={{kafka_path}}/kafka-mesos.properties
