- name: installing required repository
  get_url: url={{ maven_repo_url }} dest=/etc/yum.repos.d/{{ maven_repo_name }}

- name: copy needed repo
  copy: src=wandisco-svn.repo.j2 dest=/etc/yum.repos.d/wandisco-svn.repo

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: prepare for compilation of Mesos
  yum: name={{ item }} state=present
  with_items:
    - git
    - unzip
    - tar
    - apache-maven
    - python-devel
    - java-1.7.0-openjdk-devel
    - zlib-devel
    - libcurl-devel
    - openssl-devel
    - cyrus-sasl-devel
    - cyrus-sasl-md5
    - apr-devel
    - subversion-devel
    - apr-util-devel

- name: download sources of Mesos
  get_url: url={{ mesos_sources_zip_url }} dest={{ mesos_archive }}

- name: unarchive sources
  unarchive: src={{ mesos_archive }} dest={{ tmp_dir }}/ copy=no

- name: build Mesos, run 'bootstrap'
  command: 'chdir={{ mesos_tmp_dir }} "{{ item }}"'
  with_items:
    - ./bootstrap

- name: create 'build' dir
  file: path='"{{ mesos_tmp_dir }}"/build' state=directory

- name: complete Mesos build
  shell: "{{ item }}"
  args:
    chdir: '"{{ mesos_tmp_dir }}"/build'
  with_items:
    - ../configure
    - make -j {{ make_cores }}
    - make install
