- name: installing required repository
  get_url: url=http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo dest=/etc/yum.repos.d/epel-apache-maven.repo
  sudo: yes

- name: copy needed repo
  copy: src=wandisco-svn.repo.j2 dest=/etc/yum.repos.d/wandisco-svn.repo
  sudo: yes

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present
  sudo: yes

- name: prepare for compilation of Mesos
  yum: name={{ item }} state=present
  with_items:
    - git
    - unzip
    - tar
    - apache-maven
    - python-devel
    - java-1.7.0-openjdk-devel
    - zlib-devel
    - libcurl-devel
    - openssl-devel
    - cyrus-sasl-devel
    - cyrus-sasl-md5
    - apr-devel
    - subversion-devel
    - apr-util-devel
  sudo: yes

- name: download sources of Mesos
  get_url: url=https://github.com/apache/mesos/archive/master.zip dest=/tmp/master.zip
  sudo: yes

- name: unarchive sources
  unarchive: src=/tmp/master.zip dest=/tmp/ copy=no
  sudo: yes

- name: build Mesos, run 'bootstrap'
  command: 'chdir=/tmp/mesos-master "{{ item }}"'
  with_items:
    - ./bootstrap
  sudo: yes

- name: create 'build' dir
  file: path=/tmp/mesos-master/build state=directory
  sudo: yes

- name: complete Mesos build
  shell: "{{ item }}"
  args:
    chdir: /tmp/mesos-master/build
  with_items:
    - ../configure
    - make -j {{ make_cores }}
    - make install
  sudo: yes
