- name: check for temp directory
  file: path={{ mesos_tmp_dir }} state=directory

- name: check for 'daemonize'
  yum: name={{ daemonize_rpm }} state=present

- name: checking for docker
  yum: name=docker state=present

- name: starting docker service
  service: name=docker state=started

- name: start Mesos slave
  shell: daemonize {{ mesos_compile_dir }}/sbin/mesos-slave --master={{ mesos_master }}:5050 --containerizers={{ mesos_containers }}
