- name: check for working directory
  file: path={{ mesos_work_dir }} state=directory

- name: check for 'daemonize'
  yum: name={{ daemonize_rpm }} state=present

- name: start Mesos master
  shell: daemonize {{ mesos_compile_dir }}/sbin/mesos-master --work_dir={{ mesos_work_dir }}
